"""add student directory and signup verification flow

Revision ID: 5da962ed614a
Revises: ccceb28ebf3f
Create Date: 2026-03-29 10:02:56.603495

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5da962ed614a'
down_revision = 'ccceb28ebf3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id_card_number', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signup_verification_lookup', 'signup_verifications', ['email', 'id_card_number', 'used_at'], unique=False)
    op.create_index(op.f('ix_signup_verifications_email'), 'signup_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_signup_verifications_id_card_number'), 'signup_verifications', ['id_card_number'], unique=False)
    op.create_index(op.f('ix_signup_verifications_token'), 'signup_verifications', ['token'], unique=True)
    op.create_table('student_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id_card_number', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_directory_email'), 'student_directory', ['email'], unique=True)
    op.create_index(op.f('ix_student_directory_id'), 'student_directory', ['id'], unique=False)
    op.create_index(op.f('ix_student_directory_id_card_number'), 'student_directory', ['id_card_number'], unique=True)
    op.create_index('ix_student_directory_lookup', 'student_directory', ['institution_id', 'email', 'id_card_number'], unique=False)
    op.add_column('users', sa.Column('id_card_number', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_id_card_number'), 'users', ['id_card_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_card_number'), table_name='users')
    op.drop_column('users', 'id_card_number')
    op.drop_index('ix_student_directory_lookup', table_name='student_directory')
    op.drop_index(op.f('ix_student_directory_id_card_number'), table_name='student_directory')
    op.drop_index(op.f('ix_student_directory_id'), table_name='student_directory')
    op.drop_index(op.f('ix_student_directory_email'), table_name='student_directory')
    op.drop_table('student_directory')
    op.drop_index(op.f('ix_signup_verifications_token'), table_name='signup_verifications')
    op.drop_index(op.f('ix_signup_verifications_id_card_number'), table_name='signup_verifications')
    op.drop_index(op.f('ix_signup_verifications_email'), table_name='signup_verifications')
    op.drop_index('ix_signup_verification_lookup', table_name='signup_verifications')
    op.drop_table('signup_verifications')
    # ### end Alembic commands ###
